### ISSUE TITLE
Can't open Binder

### ISSUE THREAD

**Issue by dkweiss31** [jfeist/QuantumAlgebra.jl#6]
Hi! I'd like to explore your code a little but unfortunately the binder links don't seem to be working.

**Comment by jfeist** [comment]
I just updated the link (as binder guessed, the problem was that I recently renamed master to main). However, for new users I'd actually encourage you to check out the [full_rewrite](https://github.com/jfeist/QuantumAlgebra.jl/tree/full_rewrite) branch. The binder link within that branch has just been updated (although right now it's not super useful, as the example notebooks have not been updated. I'll try to do that soon).

**Comment by jfeist** [comment]
I just updated the examples.ipynb notebook in the [full_rewrite](https://github.com/jfeist/QuantumAlgebra.jl/tree/full_rewrite) branch to show the current capabilities and syntax of the package. I encourage you to use that (I'm planning to release it soon). The binder link in that branch has been updated to point to this version: https://mybinder.org/v2/gh/jfeist/QuantumAlgebra.jl/full_rewrite?filepath=examples.

**Comment by dkweiss31** [comment]
Awesome will definitely take a look. Thanks!

**Comment by jfeist** [comment]
FYI: I just released v1.0.0, which is based on the full_rewrite branch. Now a simple `]add QuantumAlgebra` is again sufficient to install the latest version.
